name: miniproject
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.6 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter: 
    sdk: flutter
  firebase_core: ^2.27.0
  firebase_auth: ^4.3.0
  cloud_firestore: ^4.15.8
  image_picker: ^1.0.8
  firebase_storage: ^11.6.9
  firebase_auth_web: ^5.9.8

dev_dependencies: 
  flutter_lints: ^3.0.2
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - lib/assets/images/profil.png
    - lib/assets/images/SplashScreen.jpg
    - lib/assets/images/Bg-Home Screen.jpg
    - lib/assets/images/foto.jpg
